[FEAT] Terminal Integration
leopardslab/expressPython pull request #13
Opened 2020-05-20 14:38 UTC by hv7214

**Note**
There is one issue, typing `exit` in the terminal closes the terminal widget which in turn results in blank Terminal. In future i'll apply patch for this : )

2020-05-20 14:40 UTC, hv7214 commented
@JaDogg

2020-05-21 18:55 UTC, JaDogg commented on PyRun.pro
> +QT       += core gui network
Do we need the network?

2020-05-22 03:04 UTC, hv7214 commented on PyRun.pro
> +QT       += core gui network
yeah forgot to remove it!

2020-05-23 06:56 UTC, JaDogg requested changes
This cannot be compiled on Windows as you are including header in various places. Only import if it's not windows. :)

2020-05-23 06:57 UTC, JaDogg commented on UI/mainview.h
> +#include <qtermwidget5/qtermwidget.h>
Only include this if it's not windows

2020-05-23 06:58 UTC, JaDogg commented on UI/mainview.h
> +    QTermWidget* terminal;
Don't create this object if it's windows

2020-05-23 07:24 UTC, JaDogg commented on UI/mainview.cpp
> +    terminal = new QTermWidget();
Don't do anything in this for windows.

2020-05-23 07:32 UTC, JaDogg commented
Try to do these changes and it will compile on windows without terminal support :) 
```diff
diff --git a/UI/mainview.cpp b/UI/mainview.cpp
index fae56a2..6b1857c 100644
--- a/UI/mainview.cpp
+++ b/UI/mainview.cpp
@@ -140,14 +140,22 @@ void MainView::SetupTerminal() {
 }
 
 void MainView::SetTerminal() {
+#ifndef Q_OS_WIN
     terminal = new QTermWidget();
+#endif
+
 #ifdef Q_OS_MACX
     terminal->setKeyBindings("macbook");
-#else
+#endif
+
+#ifdef Q_OS_LINUX
     terminal->setKeyBindings("linux");
 #endif
+
+#ifndef Q_OS_WIN
     terminal->setColorScheme("Tango");
     ui->dwTerminal->setWidget(terminal);
+#endif
 }
 
 void MainView::SetCompleter(CodeEditor *editor) {
@@ -221,7 +229,10 @@ MainView::~MainView() {
     this->SaveContent();
     m_workerThread->quit();
     m_workerThread->wait();
+
+#ifndef Q_OS_WIN
     delete terminal;
+#endif
     delete m_workerThread;
     delete ui;
     delete m_tute;
diff --git a/UI/mainview.h b/UI/mainview.h
index 0585aa9..a2f78a9 100644
--- a/UI/mainview.h
+++ b/UI/mainview.h
@@ -10,7 +10,9 @@
 #include <QInputDialog>
 #include <QThread>
 #include <QApplication>
+#ifndef Q_OS_WIN
 #include <qtermwidget5/qtermwidget.h>
+#endif
 
 // internal
 #include "CodeEditor/pythonsyntaxhighlighter.h"
@@ -109,7 +111,9 @@ class MainView : public QMainWindow {
     Snippets *m_snippets;
     XTute *m_tute;
     QCompleter *completer;
+#ifndef Q_OS_WIN
     QTermWidget* terminal;
+#endif
     bool m_markTute = false;
     int m_markIndex = -1;
     void ChangeFontSize(QFont font, int size);

```

2020-05-23 11:27 UTC, JaDogg approved these changes

2020-05-23 11:28 UTC, merged